apiVersion: apps/v1
kind: Deployment
metadata:
  name: staker-manager
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: staker-manager
  template:
    metadata:
      labels:
        app: staker-manager
    spec:
      containers:
      - name: staker-manager
        image: uhub.service.ucloud.cn/entropypool/staker-manager:latest
        imagePullPolicy: Always
        env:
        - name: ENV_ENVIRONMENT_TARGET
          valueFrom:
            configMapKeyRef:
              name: system-environment
              key: environment.target
        - name: ENV_CONSUL_HOST
          valueFrom:
            configMapKeyRef:
              name: system-environment
              key: environment.consul_host
        - name: ENV_CONSUL_PORT
          valueFrom:
            configMapKeyRef:
              name: system-environment
              key: environment.consul_port
        - name: ENV_BENEFIT_INTERVAL_SECONDS
          valueFrom:
            configMapKeyRef:
              name: staker-environment
              key: environment.benefit_interval_seconds
        - name: ENV_CURRENCY_REQUEST_PROXY
          valueFrom:
            configMapKeyRef:
              name: staker-environment
              key: environment.currency_proxy
        - name: ENV_CLUSTER_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace

---
apiVersion: v1
kind: Service
metadata:
  name: staker-manager
  namespace: kube-system
spec:
  ports:
  - name: http
    port: 50180
    targetPort: 50180
  - name: grpc
    port: 50181
    targetPort: 50181
  - name: prometheus
    port: 50182
    targetPort: 50182
  selector:
    app: staker-manager
